#!/bin/sh
# X Session init script

# shellcheck source=/dev/null
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

. "$XDG_CONFIG_HOME/X11/xprofile"

ssh-agent "$1"
