#!/bin/sh
# bspwmrc: window manager settings.

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# Change default cursor
xsetroot -cursor_name left_ptr

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Appearance
bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 45
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config focused_border_color "#458588"

# Rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a cmatrix state=fullscreen
bspc rule -a mtga.exe state=tiled

systemctl --user import-environment
systemctl --user start bspwm.target
