#!/usr/bin/sh
# Shell aliases definition.

# Arch User Repository Helper.
aur=paru

# Use neovim as vim.
if [ -x "$(command -v nvim)" ]; then
  alias vim="nvim"
  alias vimdiff="nvim -d"
fi

# Use eza as ls.
if [ -x "$(command -v eza)" ]; then
  alias ls="eza --icons --color=always --group-directories-first"
fi

# Use ripgrep as grep.
alias grep="rg --color=auto"

# Use aur helper as pacman.
if [ -x "$(command -v paru)" ]; then
  alias pacman='$aur'
fi

# Use bat as cat.
if [ -x "$(command -v bat)" ]; then
  bat cache --build >/dev/null 2>&1
  alias cat="bat"
  alias catt="bat --style=plain --paging=never"
fi

# Verbosity on file operations.
alias mkdir="mkdir -pv"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"

# Colored Diff.
alias diff="diff --color"

# Remove orphaned packages.
alias autoremove='if [ -z "$($aur -Qtdq)" ]; then echo "no orphan packages"; else $aur -Rns $($aur -Qtdq); fi'

# Get error messages from journalctl.
alias jctl="journalctl -p 4 -xb"
