#!/bin/sh
# global environment settings for login shells

# XDG Compliance
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/cuda"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export STACK_ROOT="$XDG_DATA_HOME/stack"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export WINEPREFIX="$XDG_DATA_HOME/wine/prefixes/default"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"

# Default Programs
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="librewolf"
export READER="zathura"
export PAGER="less"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export OPENER="xdg-open"
export DIFFPROG="nvim -d $1"

# User executables
export PATH="$PATH:$HOME/.local/bin"

# Shell
export HISTFILE="$XDG_DATA_HOME/shell_history"
export HISTSIZE=1000000
export SAVEHIST=1000000
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ALIASRC="$XDG_CONFIG_HOME/shell/aliasrc"
export BOOKMARK_ALIASRC="$XDG_CONFIG_HOME/shell/bookmark-aliasrc"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/shell/starship_prompt.toml"

# Less
export LESS=-R
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export LESSHISTFILE="-"

# Ask sudo password in dmenu
export SUDO_ASKPASS="$HOME/.local/bin/askpass"

# GTK
export GTK_IM_MODULE=cedilla

# QT
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# Fix Java on tiling window managers
export _JAVA_AWT_WM_NONREPARENTING=1

# FZF fuzzy finder
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

# ASDF Runtime proxy
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_DIR="/opt/asdf-vm"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export PATH="$ASDF_DATA_DIR/shims:$PATH"

# Golang
export GOPATH="$XDG_DATA_HOME/go"
PATH="$PATH:$GOPATH/bin"
