#!/bin/sh
# global environment settings for login shells.

# Add user binaries to PATH.
export PATH="$PATH:$HOME/.local/bin"

# XDG places.
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:$XDG_DATA_HOME/flatpak/exports/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# XDG compliance.
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export MYSQL_HISTFILE="$XDG_CACHE_HOME/mysql_history"
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export SQLITE_HISTORY="$XDG_CACHE_HOME/sqlite_history"
export STACK_ROOT="$XDG_DATA_HOME/stack"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"

# Default Programs
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="google-chrome-stable"
export READER="zathura"
export PAGER="less"
export DIFFPROG="nvim -d $1"
export SUDO_ASKPASS="$HOME/.local/bin/askpass"

# Shell
export HISTFILE="$XDG_DATA_HOME/shell_history"
export HISTSIZE=1000000
export SAVEHIST=1000000
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ALIASRC="$XDG_CONFIG_HOME/shell/aliasrc"

# GPG/SSH
unset SSH_AGENT_PID
SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)" && export SSH_AUTH_SOCK
GPG_TTY="$(tty)" && export GPG_TTY

# Less
export LESSHISTFILE="-"

# Pre-processor for viewing more types of files in the terminal.
[ -x "$(command -v batpipe)" ] && eval "$(batpipe)"
# Use batman as man
[ -x "$(command -v batman)" ] && eval "$(batman --export-env)"

# FZF fuzzy finder
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

# Golang
export GOPATH="$XDG_DATA_HOME/go"
PATH="$PATH:$GOPATH/bin"
