format = "[▎](yellow)$all"

[aws]
symbol = "  "

[character]
format = "[▎](yellow)$symbol "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "
