# Hyprland Window Manager Configuration.

## MONITORS ###################################################################
monitor = , preferred, auto, auto

## LOOK AND FEEL ##############################################################
general {
    border_size = 2
    gaps_out = 5
    col.active_border = rgba(d4be98ee)
    col.inactive_border = rgba(595959aa)

    snap {
        enabled = true
    }
}

decoration {
    rounding = 8
}

animations {
    enabled = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
    swallow_exception_regex = ^.* - Nvim$
}

## INPUT ######################################################################
input {
    kb_layout = us
    kb_variant = intl
    kb_options = lv3:caps_switch_capslock_with_ctrl
}

cursor {
    inactive_timeout = 5
}

## RULES ######################################################################
# Ignore maximize requests from all apps.
windowrule = match:class .*, suppress_event = maximize
# Apps specifics.
windowrule = match:class zenity, float on
windowrule = match:class blueman-manager, float on
windowrule = match:class com.saivert.pwvucontrol, float on
windowrule = match:class nm-connection-editor, float on
windowrule = match:class filechooser, float on
windowrule = match:class sysupgrade, float on
windowrule = match:class looking-glass-client, workspace 3

## BINDINGS ###################################################################
$mod = SUPER

# Session Control
bind = $mod, Backspace, exec, uwsm app -- wleave

# Window Status Control
bind = $mod, Q, killactive,
bind = $mod, T, togglefloating,
bind = $mod, S, togglesplit,
bind = $mod, F, fullscreen,

# Focusing
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

# Window Resize
bindm = $mod, mouse:273, resizewindow
binde = $mod, left, resizeactive, -100 0
binde = $mod, right, resizeactive, 100 0
binde = $mod, up, resizeactive, 0 -100
binde = $mod, down, resizeactive, 0 100

# Window Movement
bindm = $mod, mouse:272, movewindow
bind = $mod SHIFT, 1, movetoworkspacesilent, 1
bind = $mod SHIFT, 2, movetoworkspacesilent, 2
bind = $mod SHIFT, 3, movetoworkspacesilent, 3
bind = $mod SHIFT, 4, movetoworkspacesilent, 4
bind = $mod SHIFT, 5, movetoworkspacesilent, 5
bind = $mod SHIFT, 6, movetoworkspacesilent, 6
bind = $mod SHIFT, 7, movetoworkspacesilent, 7
bind = $mod SHIFT, 8, movetoworkspacesilent, 8
bind = $mod SHIFT, 9, movetoworkspacesilent, 9
bind = $mod SHIFT, 0, movetoworkspacesilent, 10
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, L, movewindow, r
bind = $mod, O, focuscurrentorlast

# Programs
bind = $mod, P, exec, uwsm app -- hyprshot -m region
bind = $mod, SHIFT P, exec, uwsm app -- hyprshot -m window
bind = $mod, Return, exec, uwsm app -- $TERMINAL
bind = $mod, W, exec, uwsm app -- $BROWSER
bind = $mod, E, exec, uwsm app -- pypr-client toggle filebrowser
bind = $mod, R, exec, rofi -show drun -run-command "uwsm app -- {cmd}"
bind = $mod, Escape, exec, uwsm app -- pypr-client toggle tasks
bind = $mod, backslash, exec, uwsm app -- $TERMINAL --class sessionizer sessionizer
