# Idle Configuration.

general {
    # to avoid having to press a key twice to turn on the display.
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({action=on})"
}

# Shutdown monitor after 5 min idle
listener {
    timeout = 300
    on-timeout = hyprctl dispatch "hl.dsp.dpms({action=off})"
    on-resume = hyprctl dispatch "hl.dsp.dpms({action=on})"
}
