[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "y"
run = ['''
	shell \
	  'for path in "$@"; do echo "file://$path"; done \
	  | wl-copy -t text/uri-list' \
	--confirm
	''', "yank"]
desc = "Yank files to clipboard"
